# -*- mode: ruby -*-
# vi: set ft=ruby :
$scriptWeb = <<SCRIPT
echo Installing...
sudo yum -y install epel-release
sudo yum -y install nginx
sudo cp /vagrant/nginx.conf  /etc/nginx/nginx.conf
sudo systemctl enable nginx
sudo systemctl start nginx

SCRIPT

$scriptApp = <<SCRIPT
echo Installing...
sudo yum -y install java-devel
sudo yum -y install tomcat
wget http://ftp.byfly.by/pub/apache.org/tomcat/tomcat-8/v8.5.23/bin/apache-tomcat-8.5.23.tar.gz
sudo mkdir /usr/local/tomcat
sudo tar -zxvf apache-tomcat-8.5.23.tar.gz -C /usr/local/tomcat --strip-components=1

cd /usr/local/tomcat
sudo chmod g+rwx conf
sudo chmod g+r conf/*
sudo chmod g+rwx bin
sudo chmod g+r bin/*

sudo yum -y install tomcat-admin-webapps.noarch tomcat-docs-webapp.noarch tomcat-javadoc.noarch tomcat-systemv.noarch tomcat-webapps.noarch

sudo systemctl start tomcat.service
sudo systemctl enable tomcat.service
SCRIPT
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

	config.vm.provision "shell", inline: "echo starting"
	config.vm.define "webs" do |webs|
		webs.vm.box = "sbeliakou/centos-7.4-x86_64-minimal"
		webs.vm.network "private_network", ip: "192.168.33.11"
		webs.vm.provision "shell", inline: $scriptWeb

		webs.vm.provider "virtualbox" do |v|
  			v.memory = 1024
		end	

	end

	config.vm.define "app1" do |app1|
		app1.vm.box = "sbeliakou/centos-7.4-x86_64-minimal"
		app1.vm.network "private_network", ip: "192.168.33.12"
		app1.vm.provision "shell", inline: $scriptApp
		app1.vm.provider "virtualbox" do |v|
  			v.memory = 2048
		end

	end

	config.vm.define "app2" do |app2|
		app2.vm.box = "sbeliakou/centos-7.4-x86_64-minimal"
		app2.vm.network "private_network", ip: "192.168.33.13"
		app2.vm.provision "shell", inline: $scriptApp
		app2.vm.provider "virtualbox" do |v|
  			v.memory = 2048
		end

	end

end
